imdhemy/laravel-in-app-purchases

- .gitignore
- config/purchase.php
- src/Events/AppStore/Revoke.php
- tests/Events/AppStore/EventFactoryTest.php
This is implemented based on this discussion | #40
> feature(events): support revoke notification

- .gitignore
- config/purchase.php
- src/Events/AppStore/Revoke.php
- tests/Events/AppStore/EventFactoryTest.php
This is implemented based on this discussion | #40
> Support Revoke notification from app store

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/pull_request_template.md
- CONTRIBUTING.md
**What?**
- Update the contribution guide.
- Update the bug report template.
- Update the feature request template.
- Create the pull request template.
**Why?**
Improving the community standards.
**How?**
Created the `.md` templates under the `.github` directory.
**Does your code follow the PSR-2 standard?** _(Yes|No)_.
N/A
N/A
N/A
> chore update the contribution guide

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/pull_request_template.md
- CONTRIBUTING.md
**What?**
- Update the contribution guide.
- Update the bug report template.
- Update the feature request template.
- Create the pull request template.
**Why?**
Improving the community standards.
**How?**
Created the `.md` templates under the `.github` directory.
**Does your code follow the PSR-2 standard?** _(Yes|No)_.
N/A
N/A
N/A
> chore(contribution): update the contribution guide

- CONTRIBUTING.md
Add a guideline related to the base branch.
> chore(contribution) update the contribution guide.

- .github/workflows/tests.yml
- composer.json
- composer.lock
**What?**
Updating dependencies.
**Why?**
- fixes #129
**How?**
Update lock file
**Does your code follow the PSR-2 standard?** _(Yes|No)_.
Yes
Yes
Yes
> Fix Guzzle CVEs

- bin/liap
- composer.json
- composer.lock
- src/ServiceProviders/LiapServiceProvider.php
- tests/Doubles/LiapTestProvider.php
- tests/TestCase.php
**What?**
- Fix #132 
- Update used packages.
- Update package description.
Yes
Yes
N/A
> [1.x] Fix GeneratorDouble class does not exist

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/ci.yml
- composer.json
- composer.lock
**What?**
Use php version `8`
- Updated CI
- Updated composer files
N/A
N/A
N/a
> [2.x] Use php 8

- composer.lock
**What?**
Upgraded` imdhemy/appstore-iap` (`1.0.1 => 1.1.0`)
**Why?**
`imdhemy/appstore-iap` v `1.1.0` supports getting the raw receipt responses.
N/A
No
N/A
> [1.x] Get App Store raw receipt

- composer.json
- composer.lock
**What?**
Add `openssl` extension to requirements
**Why?**
Required for JWS verification
**How?**
Updating composer.json file
N/A
Yes
N/A
> [1.x] add openssl extension to requirements

- src/ServiceProviders/EventServiceProvider.php
**What?**
A concise description of your enhancement.
**Why?**
Mention the related issue, either a feature request or a bug report.
**How?**
Describe your solution to the problem.
Answer: ...
Answer: ...
Answer: ...
> rename eventListeners config key

- src/ServerNotifications/AppStoreV2ServerNotification.php
> [1.x]: get bundle id

- composer.lock
- src/Contracts/ServerNotificationContract.php
- src/Contracts/SubscriptionContract.php
- src/ServerNotifications/AppStoreServerNotification.php
- src/ServerNotifications/AppStoreV2ServerNotification.php
- src/ServerNotifications/GoogleServerNotification.php
- src/Subscriptions/AppleSubscription.php
- tests/Unit/ServerNotifications/AppStoreServerNotificationTest.php
- tests/Unit/ServerNotifications/AppStoreV2ServerNotificationTest.php
- tests/Unit/ServerNotifications/GoogleServerNotificationTest.php
> [1.x] Get raw notification data

- src/Contracts/HasSubtype.php
- src/ServerNotifications/AppStoreV2ServerNotification.php
- tests/Unit/ServerNotifications/AppStoreV2ServerNotificationTest.php
> [1.x]: get notification subtype

- .github/ISSUE_TEMPLATE/1_Bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
| Branch?       | release/1.x |
| Bug fix?      | no                                                                  |
| New feature?  | no                        |
| Deprecations? |no        |
| Tickets       | _                  |
> [1.x] Updates bug report configs

- src/Contracts/SubscriptionContract.php
- Fix #164
| Branch?       | `1.x`  |
| Bug fix?      | no                                                                   |
| New feature?  | yes                         |
| Tickets       | Fix #164                   |
> [1.x] add v2-decoded-payload to phpdoc

- config/liap.php
- src/ServiceProviders/LiapServiceProvider.php
- Fix #140
- Fix #176
| Branch?       | 1.x for bc  |
| Bug fix?      | yes                                                                  |
| New feature?  |no                         |
| Tickets       | Fix #140 .                  |
> [1.x] [Fix] config google application credentials

- .github/workflows/update-changelog.yml
- CHANGELOG.md
| Branch?       | 1.x  |
| Bug fix?      | no                                                                   |
> [1.x] add changelog workflow

- .github/ISSUE_TEMPLATE/2_Feature_request.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/ci.yml
- .github/workflows/security-advice.yaml
- .github/workflows/update-changelog.yml
| Branch?       | master  |
| Bug fix?      | no                                                                  |
> [1.x] Update CI workflows

- UPGRADE-2.0.md
- composer.json
- composer.lock
| Branch?       | master   |
| Bug fix?      | no                                                                   |
| Deprecations? | yes        |
> [2.x] Use php 8.1

- src/Events/AppStore/DidChangeRenewalPref.php
- src/Events/AppStore/DidChangeRenewalStatus.php
- tests/Events/AppStore/DidChangeRenewalPrefTest.php
- tests/Events/AppStore/DidChangeRenewalStatusTest.php
- tests/TestCase.php
| Branch?       | 1.x  |
| Bug fix?      | yes                                                                   |
| Tickets       | Fix #221                   |
> [1.x] Fix apple events

- composer.lock
As per the title, updating the `composer.lock` file
> [1.x] Update composer.lock

- composer.json
- tests/Doubles/AppStoreTestNotificationServiceBuilderDouble.php
- tests/Doubles/JwsVerifier.php
- tests/Doubles/Laravel9/Application.php
- tests/Doubles/LiapTestProvider.php
- tests/Doubles/UrlGeneratorDouble.php
- tests/Events/AppStore/DidChangeRenewalPrefTest.php
- tests/Events/AppStore/DidChangeRenewalStatusTest.php
- tests/Events/AppStore/EventFactoryTest.php
- tests/Events/GooglePlay/EventFactoryTest.php
- tests/Events/PurchaseEventTest.php
- tests/Facades/ProductTest.php
- tests/Facades/SubscriptionTest.php
- tests/Faker.php
- tests/Handlers/AbstractNotificationHandlerTest.php
- tests/Http/Controllers/ServerNotificationControllerTest.php
- tests/Integration/Artisan/ArtisanCommandsTest.php
- tests/Subscriptions/AppStoreSubscriptionTest.php
- tests/Subscriptions/GoogleSubscriptionTest.php
- tests/TestCase.php
- tests/Unit/Console/LiapConfigPublishCommandTest.php
- tests/Unit/Console/LiapUrlCommandTest.php
- tests/Unit/Console/RequestTestNotificationCommandTest.php
- tests/Unit/Console/UrlGeneratorTest.php
- tests/Unit/ServerNotifications/AppStoreServerNotificationTest.php
- tests/Unit/ServerNotifications/AppStoreV2ServerNotificationTest.php
- tests/Unit/ServerNotifications/GoogleServerNotificationTest.php
- tests/Unit/Services/AppStoreTestNotificationServiceTest.php
- tests/Unit/ValueObjects/TimeTest.php
| Branch?       | 1.x  |
| Bug fix?      | no                                                                  |
This PR renames the tests namespace into `Imdhemy\Purchases\Tests`
> [1.x] Rename tests namespace

- src/Handlers/AppStoreV2NotificationHandler.php
- src/Handlers/HandlerFactory.php
| Branch?       | `release/1.x`|
| Bug fix?      | yes|
| New feature?  | no |
| Deprecations? | no |
| Tickets       | Fix #239 |
This modifies the visibility of handler variables.
> [1.x] Feature/make handler vars protected

- composer.lock
- phpunit.xml
- src/Services/AppStoreTestNotificationServiceBuilder.php
| Branch?       | master  |
| Bug fix?      | no                                                                   |
- Bump dependencies
- Fix missing application key
> [2.x] Bump dependencies

- .gitignore
- src/Events/GooglePlay/EventFactory.php
- src/ServiceProviders/LiapServiceProvider.php
| Branch?       | 1.x |
| Bug fix?      | yes                                                                  |
This PR is a preparation for v.2
> [1.x] Fix psalm errors

- src/ServiceProviders/LiapServiceProvider.php
| Branch?       | 1.x |
| Bug fix?      | yes                                                                   |
| New feature?  | no                        |
| Deprecations? | no       |
| Tickets       | Fix #269                  |
> [1.x] Stop setting Credentials path twice

- src/Events/PurchaseEvent.php
- tests/Events/EventFactoryTest.php
- tests/Events/PurchaseEventTest.php
| Branch?       | 1.x  |
| Bug fix?      | no                                                                  |
| Tickets       | #266                  |
> [1.x] Improve purchase event tests

- .github/pull_request_template.md
- .github/workflows/ci.yml
- composer.json
- composer.lock
| Branch?       | 1.x |
| Bug fix?      | yes/no                                                                   |
| New feature?  | yes/no                         |
| Deprecations? | yes/no        |
| Tickets       | Fix #315                   |
> [1.x] Drop php74

- .github/dependabot.yml
| Q             | A                                                                  |
|---------------|--------------------------------------------------------------------|
| Branch?       | 1.x                              |
| Bug fix?      | n/a                                                             |
| New feature?  | n/a                   |
| Deprecations? | n/a  |
| Tickets       | Fix #331             |
| License       | MIT                                                                |
- Receive monthly updates.
> [deps] Update dependabot config
